name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: nix develop .# --command go build ./...

      - name: Test
        run: nix develop .# --command go test ./...

      - name: Lint
        run: nix develop .# --command golangci-lint run ./...
